### ISSUE TITLE
Something went wrong with dep

### ISSUE THREAD

**Issue by alxmsl** [mkideal/cli#44]
1. Create simple `main.go`
```
package main

import (
	"github.com/mkideal/cli"
)

func main() {
	cli.HelpCommand("aaa")
}
```
2. Run `dep init`
3. Run `go build`
Result:
```
$: go build
# github.com/alxmsl/temp/vendor/github.com/mkideal/cli
vendor/github.com/mkideal/cli/flag.go:66: cannot convert v (type expr.Value) to type int64
vendor/github.com/mkideal/cli/flag.go:68: cannot convert v (type expr.Value) to type float64
```

**Comment by urban-1** [comment]
I get the same - how do you fix this? Is there a missing dependency?

**Comment by tyranron** [comment]
@alxmsl @urban-1 

By default `dep` uses not latest `master`, but latest version tag. 

That's why `dep` downloads for you `v0.0.1` tag of this repo instead of `master`. And in that version [such bug](https://github.com/mkideal/cli/blob/v0.0.1/flag.go#L66) is [present](https://github.com/mkideal/pkg/blob/990b42b730848cd43930433a352994783b2c60c0/expr/value.go#L59-L64) (conversting `struct` to `int` value).

But in latest `master` this is [fixed](https://github.com/mkideal/cli/blob/a9c1104566927924fdb041d198f05617492913f9/flag.go#L79).

Just use correct `[[constraint]]` for `github.com/mkideal/cli` project in your `Gopkg.toml`:
```toml 
[[constraint]]
  name = "github.com/mkideal/cli"
  branch = "master"
```

Or `[[override]]` if this is a [transitive dependency](https://github.com/golang/dep/blob/master/docs/FAQ.md#what-is-a-direct-or-transitive-dependency) in your project:
```toml
[[override]]
  name = "github.com/mkideal/cli"
  branch = "master"
```

**Comment by urban-1** [comment]
Doesn't this worth upping the version to `v0.0.2`?

(I moved to another lib in order to continue with my development :( )

**Comment by suntong** [comment]
Please take a look at #46.

**Comment by mkideal** [comment]
`v0.0.2` released totday. I'm so sorry! `v0.0.2` is late

**Comment by suntong** [comment]
Closing it now and feel free to reopen if you have any more questions.

**Comment by suntong** [comment]
So glad to have you back @mkideal ! Where have you been? :)
